version: '3.5'
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: 'host'
    environment:
      - PUID=1202
      - PGID=1200
      - TZ=Etc/UTC
    volumes:
      - /home-server/configs/radarr/config:/config
      - /home-server/media:/movies #optional
    ports:
      - 7878:7878
    restart: unless-stopped