version: '3.5'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       network_mode: 'host'
       user: 1205:1200
       environment:
            - LOG_LEVEL=debug
            - TZ=Asia/Tashkent
       ports:
            - 5055:5055
       volumes:
            - /home-server/configs/jellyseer:/app/config
       restart: unless-stopped