version: '3.5'
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: 'host'
    environment:
      - PUID=1201
      - PGID=1200
      - TZ=Etc/UTC
    volumes:
      - /home-server/configs/sonarr/config:/config
      - /home-server/media:/tv #optional
    ports:
      - 8989:8989
    restart: unless-stopped