version: '3.5'
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home-server/configs/sonarr/config:/config
      - /home-server/large-media/jellyfin/media/shows:/tv #optional
      - /home-server/large-media/qbittorrent/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped