version: '3.5'
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1203
      - PGID=1200
      - TZ=Etc/UTC
      - WEBUI_PORT=8085
    volumes:
      - /home-server/configs/qbittorrent/configs:/config
      - /home-server/media/qbittorrent/downloads:/downloads
    ports:
      - 8085:8085
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped