version: '3.5'
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: 'host'
    environment:
      - PUID=1206
      - PGID=1200
      - TZ=Etc/UTC
    volumes:
      - /home-server/configs/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped